language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install pytest pytest-cov

script:
  - env
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then py.test  --junitxml=report.xml --cov; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pytest  --junitxml=report.xml --cov; fi
  - echo "finished successfully at $(date '+ %Y-%m-%d %H:%M:%S')"
  - uname -a

branches:
  only:
    - master
    - /feature-.*/

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: blasebast
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: blasebast/sebmodules
    condition: $TOXENV == py27
	
