language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install pytest pytest-cov
  
script:
  - pytest  --junitxml=report.xml --cov
  - echo "finished successfully at $(date '+ %Y-%m-%d %H:%M:%S')"
  - echo $PYTHONPATH
  - which python
  - which pip
  - uname -a

branches:
  only:
    - master
    - /feature-.*/