language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install pytest pytest-cov

script:
  - env
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then py.test  --junitxml=report.xml --cov; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pytest  --junitxml=report.xml --cov; fi

branches:
  only:
    - master
    - /feature-.*/

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: blasebast
  password:
    secure: zet+XSEqWu8t5z34KrmVDAiaH64E2sc/ARx9Fv/oe8WbgApyElaHeI4I8LPvWjjeD3jrrwkxTIcsijG5foHzaW6VkDIYb5wtIKyvH97kH5R+0GB0gxwvLMhwrky8QVVl/wjfRd4U6jn0Aurev953UqCFiOcm56ArpWFs4dzLHKfZIKfudouoqXkU+zfbI8agtCFr4VDmIihNnDu+/qJSTaUtbI/hgkW9OCx/CLftq6ryS/IpjMTBV3NdLtMUQxElKsoYEvsugR3cGOF3wboDAtcTFF1hFrmxA/FkenoerF5vmE8DzYyrV4UXj9+ILiU+oOEAWeQBUq/EmODpIiSYEx+SNuySABeLs3yj+7kA/jQSSKZD7+EpBhmrJZJUbj/W/DQp05c60FkiuaH4GU0WYyrLc1Q6hwvQBnq5un7kxbsmQVlh6LAjvRm5qmmE8PevMxxn2Xs8UgF+rEGGfBRyMT2/q+6rsYdZdibnABONRcs2f/FPYsMfkXHNKrHCXBTTEj5Ke2xv/Tup62HkZv6bkVMhKT1cUuyXSNMOQmEU5xwikdNbSMvH6NLV1REcYnVn3JE1272ejtQNwwIr0eFxO2saX+A4pHkRdUql51t01iHjLdJ9Fdch5Eg6NBD/GFNy/jswjOsswo2DzqjND95W0J3Cn+ptrHtZf5ec6lwluco=
  on:
    tags: true
    repo: blasebast/sebmodules
