language: python
python:
  - "2.7"

install:
  - pip uninstall -y pytest
  - pip install -r requirements.txt
env:
  - PYTEST_VERSION=2.9.2 PLUGINCOMPAT_SITE=http://plugincompat.herokuapp.com
  - PYTEST_VERSION=3.0.3 PLUGINCOMPAT_SITE=http://plugincompat.herokuapp.com
script: pytest
branches:
  only:
    - master
    - /feature-.*/