language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install pytest pytest-cov

script:
  - if [[ $(python --version) | grep "Python 3" ]]; then pytest  --junitxml=report.xml --cov; fi
  - if [[ $(python --version) | grep "Python 2.7" ]]; then py.test  --junitxml=report.xml --cov; fi
  - echo "finished successfully at $(date '+ %Y-%m-%d %H:%M:%S')"
  - uname -a

branches:
  only:
    - master
    - /feature-.*/